apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: projetdevops
  namespace: argocd
spec: 
  project: default

  source:
    repoURL: https://github.com/DaoudaGning/ProjetDevops.git
    targetRevision: HEAD
    path: ./
  
  destination:
    server: https://kubernetes.default.svc
    namespace: projet-devops
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true