apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devops
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30002
