apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: devops
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3MxMjM=
  MYSQL_USER: YXBwdXNlcg==
  MYSQL_PASSWORD: YXBwcGFzczEyMw==
